name: EVE Trade
version: v6.0
version_full: Version 6.0

exclude:
    - README.md
    - netlify.toml
    - CNAME
    - LICENSE

plugins:
    - jekyll-minifier
    - jekyll-last-modified-at

jekyll-minifier:
  exclude: 'release.html'
